language: go

go:
  - "1.12.x"
  - "1.13.x"

gobuild_args: "-v -tags ci"

before_script:
  - NO_VENDOR=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get golang.org/x/tools/cmd/goimports
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls
  - go get fyne.io/fyne

script:
  - test -z "$(goimports -e -d $NO_VENDOR | tee /dev/stderr)"
  - go test -tags ci -race ./...
  - go vet -tags ci ./...
  - golint -set_exit_status $(go list -tags ci)

